import type { Product } from "./types";

const PLACEHOLDER = (seed: number) =>
  `https://picsum.photos/seed/hwahae${seed}/200/200`;

const TONER_PRODUCTS: Product[] = [
  {
    id: "p1",
    brand: "에스네이처",
    name: "아쿠아 오아시스 토너 300ml 더블 기획 (+화장솜)",
    shortName: "아쿠아 오아시스 토너",
    image: "/images/ranking/1.png",
    detailImage: "/images/products/p1.png",
    price: 19500,
    originalPrice: 53000,
    discountRate: 63,
    rating: 4.74,
    reviewCount: 27146,
    volumeLabel: "/300ml+300ml",
    volumeDetail: "300ml + 300ml",
    points: 3050,
    sampleCount: 6,
    awardDetails: [
      "2026 글로벌 픽 - 스킨케어 부문 - 수분",
      "스킨/토너 1위",
    ],
    mainCategory: "스킨케어",
    subCategory: "스킨/토너",
    keywords: ["진정", "트러블", "어성초"],
    ranking: 1,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "적합",
    drySkin: "적합",
    sensitiveSkin: "적합",
    functionalIngredients: ["어성초", "판테놀"],
    compatibilityScore: 88,
    cautionIngredientList: [],
    recommendationReasons: [
      "민감하고 예민한 피부에도 순한 사용감을 제공해요",
      "무향에 가까워 민감한 피부에도 편안한 사용감을 제공해요",
      "빠른 흡수력과 끈적임 없는 마무리감으로 데일리 활용도 높아요",
    ],
    inStock: true,
    freeShipping: true,
    volume: "300ml",
  },
  {
    id: "p2",
    brand: "라운드랩",
    name: "1025 독도 토너",
    shortName: "독도 토너",
    image: "/images/ranking/2.png",
    detailImage: "/images/products/p2.png",
    price: 15000,
    originalPrice: 22000,
    discountRate: 32,
    rating: 4.61,
    reviewCount: 28400,
    volumeLabel: "/200ml",
    points: 2250,
    mainCategory: "스킨케어",
    subCategory: "스킨/토너",
    keywords: ["각질", "진정", "pH밸런스"],
    ranking: 2,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "매우 적합",
    drySkin: "적합",
    sensitiveSkin: "적합",
    functionalIngredients: ["판테놀", "알란토인"],
    compatibilityScore: 84,
    cautionIngredientList: [],
    recommendationReasons: [
      "민감성 피부에도 부담 없이 사용할 수 있어요.",
      "주의성분이 없어 안전성이 높아요.",
      "카테고리 인기 제품으로 후기 만족도가 높아요.",
    ],
    inStock: true,
    freeShipping: true,
    volume: "200ml",
    award: { year: 2025, categoryRank: "스킨/토너 2위" },
  },
  {
    id: "p3",
    brand: "웰라쥬",
    name: "리얼 히알루로닉 블루 앰플 100",
    shortName: "히알루론산 블루 앰플",
    image: "/images/ranking/3.png",
    detailImage: "/images/products/p3.png",
    price: 18900,
    originalPrice: 28000,
    discountRate: 33,
    rating: 4.58,
    reviewCount: 8420,
    volumeLabel: "/75ml",
    points: 1890,
    mainCategory: "스킨케어",
    subCategory: "스킨/토너",
    keywords: ["수분", "보습", "히알루론산"],
    ranking: 3,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "적합",
    drySkin: "매우 적합",
    sensitiveSkin: "적합",
    functionalIngredients: ["히알루론산", "판테놀"],
    compatibilityScore: 85,
    cautionIngredientList: [],
    recommendationReasons: [
      "수분·보습 밸런스가 좋아 데일리 사용에 적합해요.",
      "주의성분 없이 안전성이 높아요.",
      "끈적임 없는 사용감으로 레이어링하기 좋아요.",
    ],
    inStock: true,
    freeShipping: true,
    volume: "75ml",
  },
  {
    id: "p4",
    brand: "토리든",
    name: "다이브인 저분자 히알루론산 세럼",
    shortName: "다이브인 히알루론산 세럼",
    image: "/images/ranking/4.png",
    price: 12500,
    originalPrice: 25500,
    discountRate: 51,
    rating: 4.69,
    reviewCount: 3050,
    volumeLabel: "/50ml",
    points: 2030,
    mainCategory: "스킨케어",
    subCategory: "스킨/토너",
    keywords: ["수분", "히알루론산", "저자극"],
    ranking: 4,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "적합",
    drySkin: "매우 적합",
    sensitiveSkin: "적합",
    functionalIngredients: ["히알루론산", "판테놀"],
    compatibilityScore: 82,
    cautionIngredientList: [],
    recommendationReasons: [
      "민감하고 예민한 피부에도 순한 사용감을 제공해요.",
      "피부 자극이 적고 안전성이 높아요.",
      "빠른 흡수력과 끈적임 없는 마무리감으로 데일리 활용도 높아요.",
    ],
    inStock: true,
    freeShipping: true,
    volume: "50ml",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  ...TONER_PRODUCTS,
  {
    id: "p7",
    brand: "닥터지",
    name: "레드 블레미쉬 클리어 수딩 크림",
    image: PLACEHOLDER(7),
    price: 28000,
    rating: 4.41,
    reviewCount: 6720,
    mainCategory: "스킨케어",
    subCategory: "크림",
    keywords: ["트러블", "진정", "수분"],
    ranking: 4,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "적합",
    drySkin: "적합",
    sensitiveSkin: "적합",
    functionalIngredients: ["센텔라", "판테놀"],
    compatibilityScore: 86,
    cautionIngredientList: [],
    recommendationReasons: [
      "트러블 진정과 보습을 동시에 케어해요.",
      "민감성 피부에도 순한 성분 조합이에요.",
      "가벼운 텍스처로 사계절 사용 가능해요.",
    ],
    inStock: true,
    freeShipping: true,
    volume: "70ml",
  },
  {
    id: "p8",
    brand: "라로슈포제",
    name: "시카밤 B5+",
    image: PLACEHOLDER(8),
    price: 32000,
    rating: 4.67,
    reviewCount: 15600,
    mainCategory: "스킨케어",
    subCategory: "크림",
    keywords: ["진정", "보습", "민감성"],
    ranking: 2,
    cautionIngredients: 0,
    allergyIngredients: 0,
    oilySkin: "보통",
    drySkin: "매우 적합",
    sensitiveSkin: "매우 적합",
    functionalIngredients: ["판테놀", "마데카소사이드"],
    compatibilityScore: 94,
    cautionIngredientList: [],
    recommendationReasons: [
      "민감·건성 피부에 최적화된 진정 크림이에요.",
      "주의성분 없이 안전성이 매우 높아요.",
      "손상된 피부 장벽 회복에 도움을 줘요.",
    ],
    inStock: true,
    freeShipping: true,
    volume: "40ml",
    award: { year: 2025, categoryRank: "크림 2위" },
  },
];

export function getProductById(id: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(
  mainCategory: string,
  subCategory: string,
  limit = 4,
): Product[] {
  return MOCK_PRODUCTS.filter(
    (p) => p.mainCategory === mainCategory && p.subCategory === subCategory,
  )
    .sort((a, b) => a.ranking - b.ranking)
    .slice(0, limit);
}

export function formatPrice(price: number) {
  return `${price.toLocaleString("ko-KR")}원`;
}

export function formatRating(rating: number) {
  return rating.toFixed(2);
}
